{{ config(
    materialized='table',
    partition_by={
        'field': 'mapping_type',
        'data_type': 'string'
    },
    cluster_by='mapping_key'
) }}

SELECT * FROM UNNEST([STRUCT<mapping_type STRING, mapping_key STRING, mapping_value STRING>
    ('data_source_flag', '1', 'USAF SURFACE HOURLY observation, candidate for merge with NCEI SURFACE HOURLY (not yet merged, element cross-checks)'),
    ('data_source_flag', '2', 'NCEI SURFACE HOURLY observation, candidate for merge with USAF SURFACE HOURLY (not yet merged, failed element cross-checks)'),
    ('data_source_flag', '3', 'USAF SURFACE HOURLY/NCEI SURFACE HOURLY merged observation'),
    ('data_source_flag', '4', 'USAF SURFACE HOURLY observation'),
    ('data_source_flag', '5', 'NCEI SURFACE HOURLY observation'),
    ('data_source_flag', '6', 'ASOS/AWOS observation from NCEI'),
    ('data_source_flag', '7', 'ASOS/AWOS observation merged with USAF SURFACE HOURLY observation'),
    ('data_source_flag', '8', 'MAPSO observation (NCEI)'),
    ('data_source_flag', 'A', 'USAF SURFACE HOURLY/NCEI HOURLY PRECIPITATION merged observation, candidate for merge with NCEI SURFACE HOURLY (not yet merged, failed element cross-checks)'),
    ('data_source_flag', 'B', 'NCEI SURFACE HOURLY/NCEI HOURLY PRECIPITATION merged observation, candidate for merge with USAF SURFACE HOURLY (not yet merged, failed element cross-checks)'),
    ('data_source_flag', 'C', 'USAF SURFACE HOURLY/NCEI SURFACE HOURLY/NCEI HOURLY PRECIPITATION merged observation'),
    ('data_source_flag', 'D', 'USAF SURFACE HOURLY/NCEI HOURLY PRECIPITATION merged observation'),
    ('data_source_flag', 'E', 'NCEI SURFACE HOURLY/NCEI HOURLY PRECIPITATION merged observation'),
    ('data_source_flag', 'F', 'Form OMR/1001 – Weather Bureau city office (keyed data)'),
    ('data_source_flag', 'G', 'SAO surface airways observation, pre-1949 (keyed data)'),
    ('data_source_flag', 'H', 'SAO surface airways observation, 1965-1981 format/period (keyed data)'),
    ('data_source_flag', 'I', 'Climate Reference Network observation'),
    ('data_source_flag', 'J', 'Cooperative Network observation'),
    ('data_source_flag', 'K', 'Radiation Network observation'),
    ('data_source_flag', 'L', 'Data from Climate Data Modernization Program (CDMP) data source'),
    ('data_source_flag', 'M', 'Data from National Renewable Energy Laboratory (NREL) data source'),
    ('data_source_flag', 'N', 'NCAR / NCEI cooperative effort (various national datasets)'),
    ('data_source_flag', 'O', 'Summary observation created by NCEI using hourly observations that may not share the same data source flag.'),
    ('data_source_flag', '9', 'Missing'),
    ('report_type_code', 'AERO', 'Aerological report'),
    ('report_type_code', 'AUST', 'Dataset from Australia'),
    ('report_type_code', 'AUTO', 'Report from an automatic station'),
    ('report_type_code', 'BOGUS', 'Bogus report'),
    ('report_type_code', 'BRAZ', 'Dataset from Brazil'),
    ('report_type_code', 'COOPD', 'US Cooperative Network summary of day report'),
    ('report_type_code', 'COOPS', 'US Cooperative Network soil temperature report'),
    ('report_type_code', 'CRB', 'Climate Reference Book data from CDMP'),
    ('report_type_code', 'CRN05', 'Climate Reference Network report, with 5-minute reporting interval'),
    ('report_type_code', 'CRN15', 'Climate Reference Network report, with 15-minute reporting interval'),
    ('report_type_code', 'FM-12', 'SYNOP Report of surface observation form a fixed land station'),
    ('report_type_code', 'FM-13', 'SHIP Report of surface observation from a sea station'),
    ('report_type_code', 'FM-14', 'SYNOP MOBIL Report of surface observation from a mobile land station'),
    ('report_type_code', 'FM-15', 'METAR Aviation routine weather report'),
    ('report_type_code', 'FM-16', 'SPECI Aviation selected special weather report'),
    ('report_type_code', 'FM-18', 'BUOY Report of a buoy observation'),
    ('report_type_code', 'GREEN', 'Dataset from Greenland'),
    ('report_type_code', 'MESOH', 'Hydrological observations from MESONET operated civilian or government agency'),
    ('report_type_code', 'MESOS', 'MESONET operated civilian or government agency'),
    ('report_type_code', 'MESOW', 'Snow observations from MESONET operated civilian or government agency'),
    ('report_type_code', 'MEXIC', 'Dataset from Mexico'),
    ('report_type_code', 'NSRDB', 'National Solar Radiation Data Base'),
    ('report_type_code', 'PCP15', 'US 15-minute precipitation network report'),
    ('report_type_code', 'PCP60', 'US 60-minute precipitation network report'),
    ('report_type_code', 'S-S-A', 'Synoptic, airways, and auto merged report'),
    ('report_type_code', 'SA-AU', 'Airways and auto merged report'),
    ('report_type_code', 'SAO', 'Airways report (includes record specials)'),
    ('report_type_code', 'SAOSP', 'Airways special report (excluding record specials)'),
    ('report_type_code', 'SHEF', 'Standard Hydrologic Exchange Format'),
    ('report_type_code', 'SMARS', 'Supplementary airways station report'),
    ('report_type_code', 'SOD', 'Summary of day report from U.S. ASOS or AWOS station'),
    ('report_type_code', 'SOM', 'Summary of month report from U.S. ASOS or AWOS station'),
    ('report_type_code', 'SURF', 'Surface Radiation Network report'),
    ('report_type_code', 'SY-AE', 'Synoptic and aero merged report'),
    ('report_type_code', 'SY-AU', 'Synoptic and auto merged report'),
    ('report_type_code', 'SY-MT', 'Synoptic and METAR merged report'),
    ('report_type_code', 'SY-SA', 'Synoptic and airways merged report'),
    ('report_type_code', 'WBO', 'Weather Bureau Office'),
    ('report_type_code', 'WNO', 'Washington Naval Observatory'),
    ('report_type_code', '99999', 'Missing '),
    ('quality_control_process_code', 'V01', 'No A or M Quality Control applied'),
    ('quality_control_process_code', 'V02', 'Automated Quality Control'),
    ('quality_control_process_code', 'V03', 'subjected to Quality Control'),
    ('wind_direction_quality_code', '0', 'Passed gross limits check'),
    ('wind_direction_quality_code', '1', 'Passed all quality control checks'),
    ('wind_direction_quality_code', '2', 'Suspect'),
    ('wind_direction_quality_code', '3', 'Erroneous'),
    ('wind_direction_quality_code', '4', 'Passed gross limits check, data originate from an NCEI data source'),
    ('wind_direction_quality_code', '5', 'Passed all quality control checks, data originate from an NCEI data source'),
    ('wind_direction_quality_code', '6', 'Suspect, data originate from an NCEI data source'),
    ('wind_direction_quality_code', '7', 'Erroneous, data originate from an NCEI data source'),
    ('wind_direction_quality_code', '9', 'Passed gross limits check if element is present')
])