SELECT
    file_uri,
    raw_data,
    SUBSTR(raw_data, 1, 4) AS total_variable_characters,
    SUBSTR(raw_data, 5, 6) AS weather_station_catalog_id,
    SUBSTR(raw_data, 11, 5) AS weather_station_wban_id,
    SUBSTR(raw_data, 16, 8) AS observation_date,
    SUBSTR(raw_data, 24, 4) AS observation_time,
    SUBSTR(raw_data, 28, 1) AS data_source_flag,
    SUBSTR(raw_data, 29, 6) AS latitude,
    SUBSTR(raw_data, 35, 6) AS longitude,
    SUBSTR(raw_data, 42, 5) AS report_type_code,
    SUBSTR(raw_data, 47, 5) AS elevation_in_meters,
    SUBSTR(raw_data, 52, 5) AS station_call_letter_id,
    SUBSTR(raw_data, 57, 4) AS quality_control_process_code,
    SUBSTR(raw_data, 61, 3) AS wind_direction_angle,
    SUBSTR(raw_data, 64, 1) AS wind_direction_quality_code,
    SUBSTR(raw_data, 65, 1) AS wind_observation_type_code,
    SUBSTR(raw_data, 66, 4) AS wind_speed_meters_per_second,
    SUBSTR(raw_data, 70, 1) AS wind_speed_quality_code,
    SUBSTR(raw_data, 71, 5) AS sky_ceiling_height_in_meters,
    SUBSTR(raw_data, 76, 1) AS sky_ceiling_quality_code,
    SUBSTR(raw_data, 77, 1) AS sky_ceiling_determination_code,
    SUBSTR(raw_data, 78, 1) AS sky_cavok_code,
    SUBSTR(raw_data, 79, 5) AS observation_distance,
    SUBSTR(raw_data, 85, 1) AS observation_distance_quality_code,
    SUBSTR(raw_data, 86, 1) AS observation_variability_code,
    SUBSTR(raw_data, 87, 1) AS observation_quality_variability_code,
    SUBSTR(raw_data, 88, 5) AS air_temperature,
    SUBSTR(raw_data, 93, 1) AS air_temperature_quality_code,
    SUBSTR(raw_data, 94, 5) AS dew_point_temperature,
    SUBSTR(raw_data, 99, 1) AS dew_point_temperature_quality_code,
    SUBSTR(raw_data, 100, 5) AS sea_level_pressure,
    SUBSTR(raw_data, 105, 1) AS sea_level_pressure_quality_code,
    SUBSTR(raw_data, 106) AS additional_data,
    ingest_timestamp,
FROM {{ ref('isd_pipeline_unnest_records') }}