{{ config(
    alias='integrated_surface_data',
    materialized='table',
    schema='publish',
) }}

SELECT
    row_hash,
    air_temperature_quality_code,
    air_temperature,
    data_source_flag,
    dew_point_temperature_quality_code,
    dew_point_temperature,
    elevation_in_meters,
    latitude,
    longitude,
    observation_distance_quality_code,
    observation_distance,
    observation_quality_variability_code,
    observation_timestamp,
    observation_variability_code,
    quality_control_process_code,
    report_type_code,
    sea_level_pressure_quality_code,
    sea_level_pressure,
    sky_cavok_code,
    sky_ceiling_determination_code,
    sky_ceiling_height_in_meters,
    sky_ceiling_quality_code,
    station_call_letter_id,
    weather_station_catalog_id,
    weather_station_wban_id,
    wind_direction_angle,
    wind_direction_quality_code,
    wind_observation_type_code,
    wind_speed_meters_per_second,
    wind_speed_quality_code,
    file_uri,
    ingest_timestamp,
FROM {{ ref('t4_isd_logic') }}