name: 'isd_pipeline'
version: '1.0.0'

profile: 'isd_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  isd_pipeline:
    +materialized: view
    isd_pipeline:
      value_maps:
        schema: isd_value_maps
