name: Deploy Cloud Functions
on:
  push:
jobs:
  deploy_functions:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        work-dir: [./event_detector, ./ingest]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Install GCloud
        run: sudo apt-get update && sudo apt-get install google-cloud-cli
      - name: Deploy Event Detector
        working-directory: ./event_detector
        run: bash deploy.sh