name: Deploy Cloud Functions
on:
  push:
jobs:
  deploy_functions:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        work-dir: [./event_detector]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: cellular-retina-427804-i7
          service_account: 'isd-pipeline-ga@cellular-retina-427804-i7.iam.gserviceaccount.com'
          credentials_json: '${{ secrets.SA_KEY }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Setup GA Service Account
        run: gcloud config set auth/impersonate_service_account isd-pipeline-ga@cellular-retina-427804-i7.iam.gserviceaccount.com
      - name: Deploy Event Detector
        working-directory: ${{ matrix.work-dir }}
        run: bash -x deploy.sh