name: Deploy Cloud Functions
on:
  push:
jobs:
  deploy_functions:
    name: Deploy Cloud Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: event_detector
            memory: 256M
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: cellular-retina-427804-i7
          service_account: 'isd-pipeline-ga@cellular-retina-427804-i7.iam.gserviceaccount.com'
          credentials_json: '${{ secrets.SA_KEY }}'
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Deploy Event Detector
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 5
        with:
          name: ${{ matrix.name }}
          runtime: 'python312'
          source_dir: ./${{ matrix.name }}/
          memory: ${{ matrix.memory }}
          entry_point: ${{ matrix.name }}