name: Test Code
on:
  push:
jobs:
  test_code:
    name: Test Code and Check Types
    runs-on: ubuntu-latest
    strategy:
      matrix:
        work-dir: [./event_detector, ./ingest]
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        working-directory: ${{ matrix.work-dir }}
        with:
          version: '1.8.3'
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Poetry Dependencies
        working-directory: ${{ matrix.work-dir }}
        run: poetry install
      - name: Pytest
        working-directory: ${{ matrix.work-dir }}
        run: |
          source .venv/bin/activate
          pytest -vv
      - name: Check MyPy
        working-directory: ${{ matrix.work-dir }}
        run: |
          source .venv/bin/activate
          mypy